version: 6
groups: []
hotkeys:
  toggle-window: []
  copy-current-path: []
  clear: []
  select-all:
    - ⌘-A
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  home:
    - Home
  end:
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-line:
    - ⌘-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top: []
  scroll-up:
    - ⌥-PageUp
  scroll-down:
    - ⌥-PageDown
  scroll-to-bottom:
    - Shift-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings: []
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab: []
  new-window: []
  profile:
    ssh:template: []
  profile-selectors:
    ssh:
      - Ctrl-=
  toggle-fullscreen: []
  close-tab: []
  reopen-tab: []
  toggle-last-tab: []
  rename-tab: []
  next-tab: []
  previous-tab: []
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  tab-1: []
  tab-2: []
  tab-3: []
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab: []
  combine-tabs: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right: []
  split-bottom: []
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector: []
  switch-profile: []
  command-selector: []
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  ctrl-c:
    - Ctrl-C
  toggle-clippy: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Tabby Default
    foreground: '#cacaca'
    background: '#171717'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff615a'
      - '#b1e969'
      - '#ebd99c'
      - '#5da9f6'
      - '#e86aff'
      - '#82fff7'
      - '#dedacf'
      - '#313131'
      - '#f58c80'
      - '#ddf88f'
      - '#eee5b2'
      - '#a5c7ff'
      - '#ddaaff'
      - '#b7fff9'
      - '#ffffff'
  lightColorScheme:
    name: Noctis
    foreground: '#40d4e7'
    background: '#052529'
    cursor: '#85efff'
    colors:
      - '#324a4d'
      - '#e66533'
      - '#49e9a6'
      - '#e4b781'
      - '#49ace9'
      - '#df769b'
      - '#49d6e9'
      - '#b2cacd'
      - '#47686c'
      - '#e97749'
      - '#60ebb1'
      - '#e69533'
      - '#60b6eb'
      - '#e798b3'
      - '#60dbeb'
      - '#c1d4d7'
    selection: '#169fb144'
  customColorSchemes: []
  fontWeight: 500
  rightClick: clipboard
  hideTabOptionsButton: true
  showTabProfileIcon: true
  copyAsHTML: false
  autoOpen: false
  warnOnMultilinePaste: false
  pasteOnMiddleClick: false
  ligatures: true
  frontend: xterm
  hideTabIndex: true
ssh:
  knownHosts:
    - host: 141.11.217.35
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 7NMRQPGZ7uq7GMAJtVpGsPwPfoOg44CazMMJLR6R5WU=
    - host: 46.3.109.12
      port: 22
      type: ecdsa-sha2-nistp256
      digest: oakEbflEW4XMlRp5CnD8S1A4B763TBCbcAokOPGQdoI=
    - host: 23.94.223.190
      port: 22
      type: rsa-sha2-256
      digest: Tw5eNoJyif3nMFQ4FcHW2BvkHbwFKtU4cG2wYF4reoI=
    - host: 46.3.97.22
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 8hfOXdlCxqQEQT1YVEjUdlDqNWGc9vfO/p5ZZTPcs0Y=
configSync:
  parts:
    hotkeys: false
    appearance: false
    vault: false
  host: ''
clickableLinks: {}
accessibility: {}
appearance:
  tabsInFullscreen: true
  css: |-
    /*

    .content.tabs-on-top {
       background-image: url("https://raw.githubusercontent.com/pawnEkko/.dotfiles/master/wallpaper/Favourite-04.jpg");     /*背景图片路径*/
       filter: opacity(100%);       /*不透明度*/
       background-repeat: no-repeat;
       background-position: 45%;
       background-size: auto 100vh;
       z-index: 1;
    }

    */
  vibrancy: true
  opacity: 0.9
  colorSchemeMode: light
  tabsLocation: left
  frame: full
hacks:
  disableGPU: true
providerBlacklist: []
commandBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
language: zh-CN
enableWelcomeTab: false
pluginBlacklist:
  - telnet
recoverTabs: false
backgroundPlugin:
  backgroundEnabled: true
  backgrounds: []
  backgroundPath: >-
    /Users/honghou/Documents/githubDoc/dotfiles-master/wallpaper/Favourite-06.jpg
clippyPlugin:
  agent: Bonzi
highlightPlugin:
  replaceProfiles:
    - id: 986666dd-dac9-4c7a-a295-9b4aff66abdd
      name: Default
      patterns:
        - enabled: true
          search: ERROR
          replace: 出错啦
        - enabled: true
          search: WARN
          replace: 警告警告
  highlightEnabled: true
  highlightPerSessionProfileMap: []
  highlightProfiles:
    - id: 60606be0-c0ff-42bc-bf77-de8a2435447f
      name: Default
      keywords:
        - text: INFO
          enabled: true
          background: true
          backgroundColor: '1'
          isRegExp: true
          isCaseSensitive: true
        - text: ERROR
          enabled: true
          background: true
          backgroundColor: '1'
          isRegExp: true
          isCaseSensitive: true
        - text: WARN
          enabled: true
          background: true
          backgroundColor: '3'
          isRegExp: true
          isCaseSensitive: true
        - text: INFO
          enabled: true
          background: true
          backgroundColor: '6'
          isRegExp: true
          isCaseSensitive: true
        - text: 错误
          enabled: true
          background: true
          backgroundColor: '1'
          isRegExp: true
          isCaseSensitive: true
        - text: 警告
          enabled: true
          background: true
          backgroundColor: '3'
          isRegExp: true
          isCaseSensitive: true
  highlightGlobalEnabled: false
